services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui

    restart: unless-stopped

    ports:
      - "${OPENWEBUI_PORT}:8080"

    environment:
      TZ: ${TZ}
      WEBUI_AUTH: "true"
      ENABLE_SIGNUP: "false"

    volumes:
      - ./data/open-webui:/app/backend/data

    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true